version: '3.8'

services:
    server:
        image: portainer/portainer-ce:latest
        command: -H tcp://tasks.agent:9001 --tlsskipverify
        volumes:
            - data:/data
        networks:
            - swarm
        ports:
            - "9443:9443"
            - "9000:9000"
            - "8000:8000"
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]
        labels:
            com.docker.container.name: "portainer"
            portainer.container.visibile: "false"
    agent:
        image: portainer/agent:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        networks:
            - swarm
        deploy:
          mode: global
          placement:
            constraints: [node.platform.os == linux]
        labels:
            portainer.container.hidden: "true"

networks:
    swarm:
        driver: overlay
        attachable: true

volumes:
    data:
